# Generated by Django 4.2.10 on 2024-02-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="adminModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adminName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.IntegerField()),
                ("instituteName", models.CharField(max_length=50)),
                ("instituteCode", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.IntegerField()),
                ("subject", models.TextField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[("1", "HOD"), ("2", "Teacher")],
                        default=2,
                        max_length=50,
                    ),
                ),
                ("password", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=100)),
                ("institute", models.CharField(max_length=50)),
            ],
        ),
    ]
