# Generated by Django 4.2.10 on 2024-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("1", "Super Admin"), ("2", "Admin"), ("3", "Faculty")],
                max_length=20,
            ),
        ),
    ]
