# Generated by Django 4.2.10 on 2024-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("1", 1), ("2", 2), ("3", 3)], max_length=20
            ),
        ),
    ]
